version: '3.4'

services:
  otc:
    image: otc-fake 
    build:
      context: otc-fake
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
    environment:
      - OTC_PORT=${OTC_PORT}
      - OTC_API=${OTC_API}
      - OTC_TIMEOUT=${OTC_TIMEOUT}
    container_name: otc-fake
    restart: always

networks:
  default:
    external:
      name: ${APP}
