version: '3.4'

services:
  utac:
    image: utac-fake
    build:
      context: utac-fake
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
    environment:
      - FAKE_UTAC_PORT=${FAKE_UTAC_PORT}
      - FAKE_UTAC_API=${FAKE_UTAC_API}
      - FAKE_UTAC_TIMEOUT=${FAKE_UTAC_TIMEOUT}
      - FAKE_UTAC_LATENCY=${FAKE_UTAC_LATENCY}
    container_name: ${APP}-utac-fake
    restart: always

networks:
  default:
    external:
      name: ${APP}
