version: '3.4'

services:
  public_backend:
    image: ${APP}-public-backend-${EXEC_ENV}:${APP_VERSION}
    build:
      context: ${BACKEND}
      target: ${EXEC_ENV}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        file_app_version: ${FILE_PUBLIC_BACKEND_APP_VERSION}
        file_dist_app_version: ${FILE_PUBLIC_BACKEND_DIST_APP_VERSION}
        port: ${PUBLIC_BACKEND_PORT}
        NPM_FIX: ${NPM_FIX}
        NPM_LATEST: ${NPM_LATEST}
        NPM_VERBOSE: ${NPM_VERBOSE}
    container_name: ${APP}-public-backend-${EXEC_ENV}
    ports:
      - ${PUBLIC_BACKEND_PORT}:${PUBLIC_BACKEND_PORT}
    environment:
      - NODE_ENV=${EXEC_ENV}
      - BACKEND_NAME=${BACKEND_NAME}
      - BACKEND_PORT=${PUBLIC_BACKEND_PORT}
      - BACKEND_SECRET=${BACKEND_SECRET}
      - APP=${APP}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_TIMEOUT=${APP_TIMEOUT}
      - APP_VERSION=${APP_VERSION}
      - PUBLIC_BACKEND=true
      - PUBLIC_BACKEND_API_UUID=${PUBLIC_BACKEND_API_UUID}
      - PUBLIC_BACKEND_USE_PREVIOUS_MONTH_FOR_DATA=${PUBLIC_BACKEND_USE_PREVIOUS_MONTH_FOR_DATA}
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PUBLIC_BACKEND_PORT}/${APP}/api/v1/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 40s

networks:
  default:
    external:
      name: ${APP}
