version: '3.4'

services:
  smtp:
    image: djfarrelly/maildev 
    container_name: ${APP}-smtp
    ports:
      - 1080:80    
    restart: always

networks:
  default:
    external:
      name: ${APP}
