version: '2'

networks:
  default:
    external:
      name: ${APP}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.22
    container_name: ${APP}-elasticsearch
    environment:
      - cluster.name=${APP}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_MEM} -Xmx${ES_MEM} -Dlog4j2.formatMsgNoLookups=True"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ports:
      - 9200:9200
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA}:/usr/share/elasticsearch/data
